function randHex(length: number): string {
    const chars = '0123456789abcdef';
    let result = '';

    for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }

    return result;
}
function rand() {
    return Math.random();
}
function pick<T>(arr: T[]): T {
    return arr[Math.floor(rand() * arr.length)];
}
function randInt(min: number, max: number) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}
function randVersion(): string {
    return `${randInt(1, 30)}.${randInt(0, 9)}.${randInt(0, 99)}`;
}
function pickLogLevel(): string {
    const n = rand();
    if (n < 0.60) return "Default";
    if (n < 0.85) return "Info   ";
    if (n < 0.95) return "Debug  ";
    if (n < 0.99) return "Error  ";
    return "Fault  ";
}
function randIp(): string {
    return `${randInt(10, 192)}.${randInt(0, 255)}.${randInt(0, 255)}.${randInt(1, 254)}`;
}

const _MACOS_PROCESSES_RAW: readonly string[] = [

    "kernel",
    "IOKit",
    "IOStorageFamily",
    "IOUSBFamily",
    "IOHIDFamily",
    "IONetworkingFamily",
    "IOGraphicsFamily",
    "IOPCIFamily",
    "IOACPIFamily",
    "IOAHCIFamily",
    "IOATAFamily",
    "IONVMeFamily",
    "IOUSBHostFamily",
    "IOFireWireFamily",
    "IOBluetoothFamily",
    "IOBlockStorageDriver",
    "IOBDStorageFamily",
    "IOCDStorageFamily",
    "IODVDStorageFamily",
    "IOSCSIArchitectureModel",
    "AppleSMC",
    "AppleACPIPlatform",
    "AppleACPIEC",
    "AppleRTC",
    "AppleAPIC",
    "AppleHPET",
    "AppleLPC",
    "AppleSMBIOS",
    "AppleHDA",
    "AppleHDACodec",
    "AppleUSBXHCI",
    "AppleUSBEHCI",
    "AppleUSBHub",
    "AppleUSBComposite",
    "AppleUSBHIDKeyboard",
    "AppleUSBHIDMouse",
    "AppleIntelCPUPowerManagement",
    "AppleThunderboltNHI",
    "AppleThunderboltIP",
    "AppleMCCSControl",
    "AppleEFIRuntime",
    "AppleIntelFramebufferAzul",
    "AppleBacklightExpert",
    "AppleGraphicsPowerManagement",
    "AppleMuxControl",
    "AppleT2",
    "AppleSecureBootKext",
    "AppleIntelMEInfo",
    "IOAccelerator",
    "IOAccelMemoryInfoCollector",

    "launchd",
    "logd",
    "notifyd",
    "cfprefsd",
    "diskarbitrationd",
    "configd",
    "fseventsd",
    "opendirectoryd",
    "directoryd",
    "memberd",
    "securityd",
    "trustd",
    "secinitd",
    "authd",
    "ctkd",
    "taskgated",
    "amfid",
    "syspolicyd",
    "transparencyd",
    "endpointsecurityd",
    "sysextd",
    "kextd",
    "kextutil",
    "oslog",
    "syslogd",
    "diagnosticd",
    "logmessaged",
    "analyticsd",
    "tailspind",
    "spindump",
    "ReportCrash",
    "crashd",
    "watchdogd",
    "warmd",
    "powerd",
    "thermalmonitord",
    "corebrightnessd",
    "hidd",
    "bluetoothd",
    "wifid",
    "airportd",
    "mDNSResponder",
    "mDNSResponderHelper",
    "captiveagentd",
    "nesessionmanager",
    "nehelper",
    "vpnd",
    "racoon",
    "networkd",
    "discoveryd",
    "locationd",
    "revisiond",
    "coreduetd",
    "symptomsd",
    "nsurlsessiond",
    "nsurlstoraged",
    "nsurlservicesd",
    "coreaudiod",
    "coremediaserverd",
    "mediaserverd",
    "mediaremoted",
    "coreauthd",
    "mds",
    "mds_stores",
    "mdworker_shared",
    "mdimport",
    "lsd",
    "apsd",
    "cloudd",
    "bird",
    "findmyd",
    "identityservicesd",
    "callservicesd",
    "imagent",
    "imtransferd",
    "rapportd",
    "rtcreportingd",
    "sharingd",
    "screenshotservices",
    "filecoordinationd",
    "distnoted",
    "uuidd",
    "fileproviderd",
    "xpcproxy",
    "secd",
    "swcd",
    "nfcd",
    "mobileactivationd",
    "mobiletimerd",
    "pluginkit",
    "lsboxd",
    "sandboxd",
    "storagekitd",
    "extensiond",
    "followupd",
    "tipsd",
    "timed",
    "aggregated",
    "pkd",
    "ndoagent",

    "UserEventAgent",
    "loginwindow",
    "SystemUIServer",
    "Dock",
    "Finder",
    "WindowServer",
    "Spotlight",
    "ScreenSaverEngine",
    "TextInputMenuAgent",
    "TextInputSwitcher",
    "AirPlayXPCHelper",
    "AirPlayUIAgent",
    "ApplePushService",
    "AXRuntimeSupport",
    "BezelServices",
    "CARenderServer",
    "CalendarAgent",
    "EscrowSecurityAlert",
    "FolderActionsDispatcher",
    "FontWorker",
    "AXVisualSupportAgent",
    "BookstoreAgent",
    "CallHistoryPluginHelper",
    "CallHistorySyncHelper",
    "CloudKeychainProxy",
    "ContactsAgent",
    "DuetExpertCenter",
    "FileSyncAgent",
    "FontUIAgent",
    "GeoServicesAgent",
    "IMAgent",
    "InstallAssistantAgent",
    "KeyboardSetupAssistant",
    "knowledgeaggd",
    "LookupViewService",
    "MobileAccessoryUpdater",
    "NotificationCenter",
    "PersonalizationPortrait",
    "PhotoLibraryAgent",
    "PIPAgent",
    "PKAgent",
    "PrinterProxy",
    "ProactiveDaemon",
    "Rationald",
    "SafariCloudHistoryPushAgent",
    "ScreenSharingAgent",
    "SpeechSynthesisServer",
    "SystemPreferences",
    "talagent",
    "TouchBarServer",
    "universalAccessAuthWarn",
    "UsageTrackingAgent",
    "WiFiAgent",
    "AddressBookSourceSync",
    "AppleSpell",
    "ARDAgent",
    "AskPermissionUI",
    "DataDetectorsSourceAccess",
    "DiagnosticExtensionPointService",
    "DockHelper",
    "ExchangeSync",
    "GKOResponder",
    "HelpData",
    "InputMethodKit",
    "iTunesCloudAgent",
    "MobileTimer",
    "NavdAgent",
    "OnBoardingKit",
    "PasteboardAgent",
    "PictureInPictureAgent",
    "PrivacyPermissionsAgent",
    "RemoteDesktopAgent",
    "SecurityAgent",
    "sharedfilelistd",
    "SiriNCService",
    "SpeechRecognitionCore",
    "Stickies",
    "TCCd",
    "TrustEvaluationAgent",
    "useractivityd",
    "usernoted",

    "accessoryupdaterd",
    "adprivacyd",
    "airdropd",
    "airplayxpcd",
    "akd",
    "anacd",
    "appstored",
    "appstoreagent",
    "AssetCacheLocatorService",
    "AssetCacheManagerService",
    "atc",
    "audiomxd",
    "autopush",
    "avconferenced",
    "backupd",
    "biomed",
    "brctl",
    "bridged",
    "calaccessd",
    "callhistoryd",
    "clpd",
    "cmpdylibd",
    "contextstored",
    "corerecents",
    "coreservicesd",
    "coresymbolicationd",
    "dataaccessd",
    "deleted",
    "diskimagesiod",
    "diskninja",
    "essentialsd",
    "familycircled",
    "familycontrols",
    "flowcryptd",
    "folderactionsd",
    "healthd",
    "homed",
    "iconservicesd",
    "installd",
    "instrumentsd",
    "languageassetd",
    "lasessionbroker",
    "linkd",
    "lskdd",
    "lsregister",
    "mbimageupdater",
    "mediaanalysisd",
    "mediaaccessibilityd",
    "medialibraryd",
    "navd",
    "networkserviceproxy",
    "newsd",
    "passd",
    "photolibraryd",
    "photoanalysisd",
    "photoprocessingd",
    "powerlogHelperd",
    "proactived",
    "quarantined",
    "recognitiond",
    "replayd",
    "routinetrakerd",
    "sessionagent",
    "silentsd",
    "sirittsd",
    "slpd",
    "softwareupdated",
    "sotd",
    "stapled",
    "storeaccountd",
    "storedownloadd",
    "storeinappd",
    "storekitagent",
    "storelegacyd",
    "storeuid",
    "ubd",
    "weatherd",
    "xcactivityloguserland",
    "XprotectService",
    "xpcd",
    "yoinkd",
    "AOSPushRelay",
    "AOSNotification",
    "APFSUserAgent",
    "mobileassetd",
    "assetsd",
    "ndrd",
    "ioupsd",
    "batteryupdater",
    "smc",
    "smcd",
    "eapolclient",
    "SubmitDiagInfo",
    "diagnosticsreporterd",
    "ctkahp",
    "keystored",
    "com.apple.security.pboxd",

    "com.apple.AddressBook.SourceSync",
    "com.apple.AppSandboxService",
    "com.apple.AssetCacheService",
    "com.apple.audio.SandboxHelper",
    "com.apple.automator.automatorservice",
    "com.apple.biometrickitd",
    "com.apple.bsd.dirhelper",
    "com.apple.CalendarAgent",
    "com.apple.callhistory.sync-helper",
    "com.apple.cfnetwork.cfnetworkagent",
    "com.apple.coredata.cloudkit",
    "com.apple.coremedia.remotepolicy",
    "com.apple.coreservices.appleevents",
    "com.apple.coreservices.quarantine-resolver",
    "com.apple.coreservices.uiagent",
    "com.apple.DataDetectors.service",
    "com.apple.diskimages.fileaccess",
    "com.apple.duetexpertcenter.stream-endpoint-prediction-service",
    "com.apple.familycontrols.useragent",
    "com.apple.FileCoordination",
    "com.apple.FileSyncAgent.PHD",
    "com.apple.findmymac.findmymacmessenger",
    "com.apple.geod",
    "com.apple.iCloudHelper",
    "com.apple.icloud.FindMyDeviceViewService",
    "com.apple.iconservices.iconservicesagent",
    "com.apple.imageCaptureService",
    "com.apple.InputMethodKit.TextReplacementService",
    "com.apple.intelligenceplatformd",
    "com.apple.itunes.aml.scan",
    "com.apple.knowledge-agent",
    "com.apple.languageassetd",
    "com.apple.lsd.mapdb",
    "com.apple.mailservices",
    "com.apple.mediaanalysisd",
    "com.apple.MobileAccessoryUpdater",
    "com.apple.nehelper",
    "com.apple.networkserviceproxy.useragent",
    "com.apple.NotesMigratorService",
    "com.apple.nsurlsessiond",
    "com.apple.passd",
    "com.apple.photoanalysisd",
    "com.apple.photoLibraryMigrationUtility",
    "com.apple.pkd",
    "com.apple.PrivilegedHelperTool",
    "com.apple.rapportd-user",
    "com.apple.RemoteDesktop.agent",
    "com.apple.routined",
    "com.apple.SafariCloudHistoryPushAgent",
    "com.apple.sandboxd",
    "com.apple.siri.morphunassetsupdater",
    "com.apple.siriinferenced",
    "com.apple.softwareupdated",
    "com.apple.speech.speechsynthesisd",
    "com.apple.speechrecognitiond",
    "com.apple.storeaccountd",
    "com.apple.storeassetd",
    "com.apple.storekitagent",
    "com.apple.syncserver",
    "com.apple.tccd",
    "com.apple.tipsd",
    "com.apple.TrustEvaluationAgent",
    "com.apple.ubd",
    "com.apple.universalaccessd",
    "com.apple.UsageTrackingAgent",
    "com.apple.videoconferenced",
    "com.apple.xpc.activity.monitor",
    "com.apple.xpc.amsaccountsd",
    "com.apple.xpc.amsengagementd",
    "com.apple.xpc.amspushagent",
    "com.apple.xpc.cloudd",
    "com.apple.xpc.coreauthd",
    "com.apple.xpc.coreml.modelservice",
    "com.apple.xpc.diagnostic_extensions.xpc",
    "com.apple.xpc.duetactivityschedulerd",
    "com.apple.xpc.fmfd",
    "com.apple.xpc.installcoordinationd",
    "com.apple.xpc.itunesstored",
    "com.apple.xpc.loginwindow",
    "com.apple.xpc.nsurlsessiond",
    "com.apple.xpc.osanalytics",
    "com.apple.xpc.rcd",
    "com.apple.xpc.sbd",
    "com.apple.xpc.seld",
    "com.apple.xpc.sessiond",
    "com.apple.xpc.siriinferenced",
    "com.apple.xpc.siriknowledged",
    "com.apple.xpc.timed",
    "com.apple.xpc.usagetracking",
    "com.apple.xpc.wildduckagent",
    "com.apple.MTLCompilerService",
    "com.apple.metaldeviced",
    "com.apple.gpud",
    "com.apple.gpuRestartd",
    "com.apple.CoreML.Framework.xpc",
    "com.apple.neuralengineserviced",
    "com.apple.photoprocessingd",
    "com.apple.vision.FaceService",
    "com.apple.vision.PhotoAnalysisService",
    "com.apple.accessibility.AXVisualSupportAgent",
    "com.apple.accessibility.heard",
    "com.apple.accounts.AccountsProviderCacheService",
    "com.apple.accountsd",
    "com.apple.amsaccountsd",
    "com.apple.analyticsd",
    "com.apple.ap.adprivacyd",
    "com.apple.apiservicesd",
    "com.apple.appleseed.seedusaged",
    "com.apple.AppleSpell.service",
    "com.apple.assistant_service",
    "com.apple.assistantd",
    "com.apple.avfoundation.xpc",
    "com.apple.awdd",
    "com.apple.BackgroundTaskManagement",
    "com.apple.biometricd",
    "com.apple.bluetoothuserd",
    "com.apple.cache_delete",
    "com.apple.callkit.callservicesd",
    "com.apple.CaptiveNetworkAssistant",
    "com.apple.cmio.IIDCVideoAssistant",
    "com.apple.CoreDataContainers",
    "com.apple.coreduet.sync.xpc",
    "com.apple.corecaptured",
    "com.apple.coregraphics.cghidserverd",
    "com.apple.CoreLocationAgent",
    "com.apple.coreml.backgrounddownloads",
    "com.apple.coreml.modelcompiler",
    "com.apple.CrashReporterSupportHelper",
    "com.apple.DeferredInstallService",
    "com.apple.diskmanagementd",
    "com.apple.disksdiagd",
    "com.apple.displaypolicyd",
    "com.apple.dt.instruments.remotedserver",
    "com.apple.DuetHeuristic-BM",
    "com.apple.emailanalysisd",
    "com.apple.eslogger",
    "com.apple.exchangewebservices",
    "com.apple.familynotificationd",
    "com.apple.fileprovider.ephemeral",
    "com.apple.fileprovider.embedded",
    "com.apple.financed",
    "com.apple.focusd",
    "com.apple.foundationd",
    "com.apple.gamecenter.daemon",
    "com.apple.geod.maposd",
    "com.apple.gpumemd",
    "com.apple.hid.matchingd",
    "com.apple.homeenergyd",
    "com.apple.ifplusd",
    "com.apple.imklaunchagent",
    "com.apple.iSight.helper",
    "com.apple.ituneslibraryd",
    "com.apple.itunesstored",
    "com.apple.keyboardservicesd",
    "com.apple.kExtAuditd",
    "com.apple.knowledged",
    "com.apple.ldu",
    "com.apple.maps.mapspushd",
    "com.apple.mdmd",
    "com.apple.mediaPlaybackCore.xpc",
    "com.apple.metallibraryd",
    "com.apple.mlcomputed",
    "com.apple.ModelIO.AssetLoader",
    "com.apple.nicid",
    "com.apple.nsurldownloaddaemon",
    "com.apple.ocspd",
    "com.apple.osanalyticsd",
    "com.apple.photokit.photolibraryd",
    "com.apple.powerlog.plaharvester",
    "com.apple.privatecloudcomputed",
    "com.apple.quicklook.qlmanage",
    "com.apple.quicklookd",
    "com.apple.rapportd",
    "com.apple.recentsd",
    "com.apple.remindd",
    "com.apple.restoreagentd",
    "com.apple.rubiconservice",
    "com.apple.screensharingd",
    "com.apple.seld",
    "com.apple.sensors",
    "com.apple.servicemanagementd",
    "com.apple.shazamd",
    "com.apple.shortcuts.BackgroundShortcutRunner",
    "com.apple.siricore",
    "com.apple.siriknowledged",
    "com.apple.siritts",
    "com.apple.sociald",
    "com.apple.spotlight.IndexAgent",
    "com.apple.syncdefaultsd",
    "com.apple.triald",
    "com.apple.video.videod",
    "com.apple.wallpaperd",
    "com.apple.webbookmarksd",
    "com.apple.wifianalyticsd",
    "com.apple.CoreSimulator.CoreSimulatorService",
    "com.apple.dt.debugserver",
    "com.apple.osanalytics.osanalyticshelper",
    "com.apple.protectedcloudstorage.protectedcloudkeysyncing",
    "com.apple.SystemConfiguration.SCNetworkReachability",
    "com.apple.cfnetwork.AuthBrokerAgent",
    "com.apple.icloud.searchpartyuseragent",
    "com.apple.itunes.aml.subscriptions",
    "com.apple.nfcd.helper",
    "com.apple.passd.libraryupdater",
    "com.apple.pluginkit.pkd",
    "com.apple.private.alloy.continuity.activity",
    "com.apple.private.alloy.continuity.encryption",
    "com.apple.private.alloy.filetransfer",
    "com.apple.private.alloy.kvs",
    "com.apple.private.alloy.nearby",
    "com.apple.private.alloy.notificationproxy",
    "com.apple.private.alloy.safariactivities",
    "com.apple.private.alloy.willow",
    "com.apple.security.cloudkeychainproxy3",
    "com.apple.security.FDERecoveryAgent",
    "com.apple.storeuid",
    "com.apple.studentd",
    "com.apple.translationd",
    "com.apple.universalaccessd.UIKit",
    "com.apple.videosubscriptionsd",
    "com.apple.WebKit.WebContent",
    "com.apple.WebKit.Networking",
    "com.apple.WebKit.GPU",
    "com.apple.xpc.SMAppServiceStatusMonitor",
    "com.apple.xpc.launchd.oneshot",
    "com.apple.xpc.open",
    "com.apple.symptomsd",
    "com.apple.icloud.searchpartyd",
    "com.apple.CoreSync",
    "com.apple.MobileDocuments",
    "com.apple.account.caldav.sync",
    "com.apple.account.carddav.sync",

    "trustdadmin",
    "KeychainSyncingOverIDSProxy",
    "CryptoTokenKit",
    "XProtect",
    "XProtectRemediator",
    "GateKeeper",
    "PrivacyTCA",
    "privacyd",
    "tccd",
    "tccutil",
    "bputil",
    "csrutil",
    "kmutil",
    "cryptexctl",
    "codesign",
    "spctl",
    "disklockd",
    "FileVaultHelper",
    "SecKeychainCircleStatus",
    "SecurityFoundation",
    "Authorization",
    "csdinit",
    "SecureBootTool",
    "MRT",
    "com.apple.TCC.tccd",
    "com.apple.security.keychain-circle-notification",
    "com.apple.security.agent",
    "com.apple.SecurityServer",
    "com.apple.ct.monitor",
    "OCSP",
    "CertificateService",
    "com.apple.authd",
    "com.apple.AuthorizationHost",
    "com.apple.coreauthd",
    "com.apple.Gatekeeper.assessmentd",
    "com.apple.EscrowService",
    "com.apple.ctkd.slot-plugin",
    "com.apple.ctkd.token-plugin",
    "com.apple.DiskArbitration.diskarbitrationd",
    "com.apple.securityd.xpc",
    "com.apple.trustd.agent",
    "com.apple.FamilySharingService",
    "com.apple.security.FDE",
    "DataVaultProtect",
    "DataVaultService",
    "com.apple.ManagedClient.cloudconfigurationd",
    "com.apple.ManagedClient.enroll",
    "com.apple.devicecheckd",
    "com.apple.fpsd",
    "com.apple.opendirectoryd",
    "com.apple.private.openssh-darwin",
    "com.apple.RemoteManagement.ARDAgent",
    "com.apple.ProtectedCloudStorage",
    "com.apple.security.CKKSviewManager",
    "com.apple.security.circlejoinrequested",
    "com.apple.security.certstorage",
    "com.apple.securityuploadd",
    "AKSCd",
    "com.apple.akd",
    "com.apple.security.keychainaccess",
    "com.apple.loginwindow.auth",

    "NetworkLinkConditioner",
    "networkd_privileged",
    "pktmnglr",
    "SCMonitor",
    "IPConfiguration",
    "IPMonitor",
    "netbiosd",
    "smbd",
    "nfsd",
    "ftpd",
    "sshd",
    "httpd",
    "portmap",
    "rpcbind",
    "automountd",
    "autofsd",
    "nfsuserd",
    "mountd",
    "statd",
    "lockd",
    "netinfod",
    "dnsmasq",
    "named",
    "unbound",
    "dnsextd",
    "pfd",
    "AWD",
    "pktmnglrd",
    "com.apple.networkd.context_manager",
    "com.apple.networkextension",
    "com.apple.nwpathd",
    "com.apple.networkserviceproxy.useragent",
    "com.apple.mDNSResponder",
    "com.apple.discoveryd",
    "com.apple.captiveagentd",
    "com.apple.nesessionmanager",
    "com.apple.wifid",
    "com.apple.airportd",
    "com.apple.bluetoothd",
    "com.apple.BTServer",
    "com.apple.bluetoothaudiod",
    "com.apple.bluetoothUIServer",
    "BTLEServerAgent",
    "bluetoothReporter",
    "com.apple.bluetooth.le",
    "airplayd",
    "airplayreciever",
    "com.apple.airplay",
    "ContinuityCamera",
    "com.apple.continuitypairing",
    "com.apple.airdropd",
    "com.apple.rapportd",
    "handoffagent",
    "AirDropTogetherAgent",
    "com.apple.WiFiVelocity",
    "com.apple.eapolclient",
    "com.apple.networkd",
    "com.apple.network.identification",
    "com.apple.pfd",
    "com.apple.wireless.WiFiAgent",

    "diskmanagementd",
    "fsck_apfs",
    "fsck_hfs",
    "newfs_apfs",
    "hdiutil",
    "diskutil",
    "AppleRAID",
    "CoreStorage",
    "APFS",
    "msdosfs",
    "ntfs",
    "exfatfs",
    "MobileBackup",
    "TMHelperAgent",
    "TMSafetyNet",
    "TimeMachineStatus",
    "asr",
    "bom",
    "expandd",
    "fmfd",
    "SpotlightNetHelper",
    "com.apple.diskspaced",
    "com.apple.fseventsd",
    "com.apple.DiskManagement",
    "com.apple.QuarantineEvents",
    "com.apple.LaunchServices.lsboxd",
    "com.apple.iconservices.store",
    "com.apple.CoreStorage",
    "com.apple.CoreRAID",
    "com.apple.storagekitd",
    "NSFileProviderService",
    "com.apple.TimeMachine",
    "com.apple.backupd",
    "com.apple.MobileBackup",
    "com.apple.FileSyncAgent",
    "com.apple.bird",
    "CloudSyncingBirdAgent",
    "iCloudDrive",
    "com.apple.cloudpaird",
    "com.apple.diskutil",
    "com.apple.fileprovider",
    "com.apple.fileprovider.nonreplicated",
    "com.apple.filesystems",
    "com.apple.filecoordination",
    "com.apple.SharingHelper",
    "com.apple.fileProviderXPC",
    "com.apple.diskarbitrationd",
    "com.apple.diskimages",
    "com.apple.APFSUserAgent",
    "com.apple.DiskArbitrationUI",
    "com.apple.diskspacediagnosticd",
    "com.apple.lsar",
    "com.apple.nfsd",
    "com.apple.automountd",
    "com.apple.storeinappd",
    "com.apple.DiskImages.FileBackingStore",
    "com.apple.diskimagesiod",
    "com.apple.diskninja",
    "com.apple.hdiutil",
    "com.apple.newfs_apfs",

    "SkyLight",
    "CoreGraphics",
    "com.apple.WindowServer",
    "com.apple.windowserver.active",
    "CarPlayAgent",
    "SceneKit",
    "Metal",
    "MetalPerformanceShaders",
    "CoreImage",
    "CoreAnimation",
    "CoreVideo",
    "QuartzComposer",
    "DisplayServices",
    "AppleGraphicsControl",
    "AGX",
    "AGXMetal",
    "com.apple.AGXCompilerService",
    "AppleIntelGraphicsFramebuffer",
    "displaypolicyd",
    "brightnesscontrol",
    "NightShiftAgent",
    "TrueToneAgent",
    "com.apple.NightShift",
    "com.apple.TrueTone",
    "colorsyncd",
    "com.apple.ColorSync",
    "screencaptured",
    "screenshotsd",
    "com.apple.coregraphics",
    "com.apple.SkyLight",
    "com.apple.CoreDisplay",
    "com.apple.WindowServer.active",
    "com.apple.iokit.IOGraphicsFamily",
    "com.apple.driver.AppleBacklightExpert",
    "com.apple.driver.AppleMCCSControl",
    "com.apple.driver.DspFuncLib",
    "com.apple.coremedia.videoqueue",
    "com.apple.gpumemd",
    "com.apple.metaldeviced",
    "com.apple.MTLCompilerService",

    "AVFoundation",
    "CoreAudio",
    "AudioComponentRegistrar",
    "AudioToolbox",
    "com.apple.audio.coreaudiod",
    "com.apple.audio.AudioComponentRegistrar",
    "com.apple.audio.AudioSession",
    "com.apple.mediaremoted",
    "com.apple.mediaaccessibilityd",
    "com.apple.coremedia",
    "com.apple.avfaudio",
    "CoreMIDI",
    "MIDIServer",
    "coremidi",
    "com.apple.midiserver",
    "AudioServerPlugin",
    "VideoToolbox",
    "CoreMediaIO",
    "com.apple.coremediad",
    "com.apple.audio.audiod",
    "com.apple.audio.avconferenced",
    "com.apple.cmio.VDCAssistant",
    "com.apple.cmio.AVCAssistant",
    "com.apple.cmio.IIDCAssistant",
    "com.apple.CoreAudio.HALPlugIn",
    "com.apple.AMPLibrary",
    "com.apple.itunescloudd",
    "com.apple.airplay.airplayxpcd",
    "com.apple.audio.systemsoundserverd",
    "systemsoundserverd",
    "com.apple.coreaudio.audiomxd",
    "com.apple.audiomxd",
    "com.apple.coremediaio",
    "com.apple.streamingzip",
    "com.apple.mediastream.mstreamd",
    "mstreamd",
    "com.apple.audio.SandboxHelper",
    "com.apple.mediaPlaybackCore.xpc",
    "com.apple.coremedia.remotepolicy",
    "com.apple.videotoolbox",

    "assistantd",
    "siriknowledged",
    "SiriInferenceService",
    "SiriTTSService",
    "com.apple.siri",
    "com.apple.assistantd",
    "naturallanguaged",
    "com.apple.naturallanguage",
    "intelligenced",
    "coreknowledged",
    "suggestd",
    "com.apple.suggestd",
    "com.apple.proactived",
    "speechrecognitiond",
    "com.apple.speechrecognitiond",
    "CoreML",
    "CreateML",
    "MLCompute",
    "com.apple.neuralengineserviced",
    "com.apple.mlcomputeserviced",
    "com.apple.coremlserviced",
    "BNNS",
    "com.apple.coreml",
    "com.apple.intelligenced",
    "com.apple.knowledged",
    "com.apple.coreknowledged",
    "com.apple.siriTTSd",
    "com.apple.NaturalLanguage",
    "com.apple.suggestions",
    "com.apple.VisionKit",

    "com.apple.apsd",
    "APNSAgent",
    "pushd",
    "com.apple.notifyd",
    "UserNotificationsServer",
    "com.apple.usernotificationsd",
    "UNUserNotificationCenter",
    "CFUserNotification",
    "com.apple.CFNotificationCenterDistributedNotificationPost",
    "com.apple.distributed_notifications",
    "DarwinNotificationCenter",
    "com.apple.pushNotificationService",
    "com.apple.notificationcenterui",
    "com.apple.NotificationCenter",
    "com.apple.usernoted",
    "com.apple.notificationd",
    "com.apple.apsd.helper",
    "com.apple.CommCenter.coretelephony",
    "com.apple.icloud.fmfd",
    "com.apple.AOSNotification",

    "com.apple.sharingd",
    "continuity",
    "com.apple.continuity",
    "com.apple.handoffagent",
    "AirDropUI",
    "com.apple.airdropui",
    "com.apple.AirDrop",
    "handoff",
    "com.apple.ContinuityCamera.CameraViewer",
    "com.apple.screentime",
    "com.apple.screentimed",
    "com.apple.ScreenTimeAgent",
    "com.apple.ContinuityUI",
    "com.apple.private.alloy.continuity",
    "com.apple.private.alloy.woodpecker",
    "com.apple.ScreenSharingMenulet",
    "com.apple.universalclipboard",
    "com.apple.AirPlayReceiver",
    "com.apple.continuity.activity",
    "com.apple.AirDrop.service",

    "dtrace",
    "instruments",
    "lldb",
    "debugserver",
    "symbolicatord",
    "atos",
    "vmmap",
    "heap",
    "leaks",
    "malloc_history",
    "com.apple.dt.Instruments",
    "com.apple.dt.remotedserver",
    "dtrace.helper",
    "kperf",
    "kdcr",
    "com.apple.kdcr",
    "com.apple.kperf",
    "com.apple.DTrace",
    "com.apple.oslog",
    "com.apple.CoreSymbolication",

    "com.apple.cloudconfigurationd",
    "cloudconfigurationd",
    "NSUbiquitousKeyValueStoreService",
    "com.apple.NSUbiquitousKeyValueStore",
    "NSFileCoordinator",
    "com.apple.OsXSurrogateService",
    "com.apple.icloud.drive",
    "com.apple.iCloudDrive",
    "com.apple.ituneslibraryd",
    "com.apple.photokit.sync",
    "com.apple.private.coreos.icloud.sync",
    "com.apple.icloud.searchpartyuseragent",
    "com.apple.nsurlstoraged",
    "com.apple.CoreSync",
    "com.apple.account.caldav.sync",
    "com.apple.account.carddav.sync",
    "com.apple.icloud.searchpartyd",
    "com.apple.MobileDocuments",
    "com.apple.cloudconfigurationd.helper",
    "com.apple.syncagentd",

    "com.apple.powerd",
    "com.apple.thermalmonitord",
    "com.apple.ioupsd",
    "com.apple.batteryupdater",
    "com.apple.smcd",
    "smckit",
    "powermetrics",
    "com.apple.powermetrics",
    "caffeinate",
    "com.apple.PowerManagement",
    "com.apple.powerd.sleep-wake-failure",
    "com.apple.powerlog",
    "com.apple.thermal",
    "com.apple.smc",
    "com.apple.coreduet.powerd",
    "com.apple.pmTool",
    "com.apple.powerd.sleepservicesd",
    "com.apple.sleepservicesd",
    "com.apple.iokit.IOPMrootDomain",
    "com.apple.powerlog.plaharvester.helper",

    "com.apple.locationd",
    "coreLocationHelper",
    "com.apple.CoreLocationAgent",
    "mapsupdate",
    "com.apple.maps",
    "mapspushd",
    "com.apple.navd",
    "geofenced",
    "com.apple.geofenced",
    "wbdaemon",
    "com.apple.weatherd",
    "com.apple.geod.maposd",
    "com.apple.locationd.bundle",
    "com.apple.maps.mapspushd",
    "com.apple.geod.locationfeed",

    "launchctl",
    "sc_helper",
    "kcproxy",
    "PerfPowerServicesExtended",
    "PerfPowerServicesDaemon",
    "OSKextLoad",
    "OSKextUnload",
    "KextAudit",
    "BootCacheControl",
    "SoftwareUpdateNotificationManager",
    "mas",
    "storeagent",
    "com.apple.lsd",
    "com.apple.oslog.helper",
    "com.apple.SafariSandboxBroker",
];

const MACOS_PROCESSES: string[] = [...new Set(_MACOS_PROCESSES_RAW)];
(function padToThousand() {
    let i = MACOS_PROCESSES.length;
    while (MACOS_PROCESSES.length < 1000) {
        MACOS_PROCESSES.push(`com.apple.xpc.svc.ext${i++}`);
    }
})();

const INTERFACES = [
    "en0", "en1", "en2", "en3",
    "utun0", "utun1", "utun2",
    "lo0", "bridge0", "vmnet1", "vmnet8", "anpi0", "pdp_ip0",
];
const VOLUMES = [
    "Macintosh HD",
    "Macintosh HD - Data",
    "Preboot",
    "Recovery",
    "VM",
    "Update",
    "System",
];
const KEXT_LOAD_MESSAGES = [
    "loaded and started",
    "registered in IOKit plane",
    "matched and attached",
    "probe succeeded",
    "start() returned true",
    "resource load complete",
    "personality matched",
];
const DAEMON_INIT_PHRASES = [
    "initializing subsystems",
    "loading configuration",
    "establishing IPC channel",
    "registering with launchd",
    "acquiring sandbox token",
    "starting main runloop",
    "binding to bootstrap port",
    "reading preferences",
    "warming cache",
    "validating entitlements",
    "connecting to WindowServer",
    "registering mach port",
    "opening dispatch queue",
    "synchronizing state",
    "verifying code signature",
];
const APFS_OPS = [
    "mounting volume",
    "verifying container",
    "activating data volume",
    "fsck completed with no errors",
    "journal replay complete",
    "snapshot mount succeeded",
    "container cs 1 role System",
    "seal verified",
];
const SECURITY_EVENTS = [
    "trust evaluation completed",
    "keychain unlocked",
    "code signature verified",
    "sandbox policy applied",
    "authorization granted",
    "certificate chain validated",
    "OCSP staple verified",
    "entitlement check passed",
    "system policy assessment: allow",
];
const NETWORK_EVENTS = [
    "link state changed to active",
    "DHCP DISCOVER sent",
    "DHCP OFFER received",
    "DHCP ACK received",
    "IPv6 address configured",
    "DNS configuration applied",
    "interface attached to network",
    "NWPathMonitor: satisfied",
    "captive portal probe: free",
];

let _bootMs = 0;
function nextTimestamp(): string {
    _bootMs += randInt(2, 55);
    const ms = _bootMs % 1000;
    const sTotal = Math.floor(_bootMs / 1000);
    const sec = sTotal % 60;
    const minTot = Math.floor(sTotal / 60);
    const min = minTot % 60;
    const hr = Math.floor(minTot / 60);
    const today = new Date();
    const dayName = today.getDate();
    const monthName = today.toLocaleString('default', { month: 'long' });

    return `${monthName} ${dayName}  ${String(hr).padStart(2, "0")}: ${String(min).padStart(2, "0")}: ${String(sec).padStart(2, "0")}. ${String(ms).padStart(3, "0")}`;
}

type MsgFn = (process: string, pid: number) => string;
const MESSAGE_GENERATORS: MsgFn[] = [

    (p) => `${p}::start()`,
    (p) => `${p}::probe() -- matched`,
    (p) => `IOService::waitForService(IOService * "${p}") timed out after 10 seconds`,
    (p) => `${p}: vendor 0x${randHex(4)}, device 0x${randHex(4)}, rev 0x${randHex(2)}`,
    (p) => `kext ${p} ${pick(KEXT_LOAD_MESSAGES)}`,
    (p) => `${p}: allocated ${randInt(32, 1024)}MB for framebuffer at 0x${randHex(12)}`,
    (p) => `${p}: firmware version ${randVersion()}`,
    (p) => `${p}: interrupt mask 0x${randHex(8)}, vector ${randInt(0, 255)}`,
    (p) => `IOKit: ${p} registered with service plane`,
    (p, pid) => `${p}::stop() called — detaching from ${MACOS_PROCESSES[randInt(0, MACOS_PROCESSES.length - 1)]} [pid ${pid}]`,

    (p) => `Spawning ${p}`,
    (p) => `Service <${p}> enabled`,
    (p) => `${p} exited with code ${randInt(0, 1)}`,
    (p) => `XPC connection established with ${p}`,
    () => `Received SIGTERM — shutting down`,
    (p) => `Bootstrapping: ${p}`,
    (p) => `com.apple.xpc.launchd: ${p} endpoint created`,
    (p) => `throttle interval expired — respawning ${p}`,
    (p) => `Bootstrap server: ${p} port registered`,

    (p) => `${pick(DAEMON_INIT_PHRASES)}`,
    () => `version ${randVersion()} starting`,
    () => `listening on 127.0.0.1:${randInt(1024, 49151)}`,
    () => `connected to ${MACOS_PROCESSES[randInt(0, MACOS_PROCESSES.length - 1)]}`,
    () => `cache invalidated — rebuilding index`,
    () => `${randInt(1, 32)} worker threads created`,
    () => `mach port 0x${randHex(8)} acquired`,
    (p) => `loaded ${randInt(1, 512)} preferences from /Library/Preferences/${p}.plist`,
    (p) => `dispatch source activated on queue com.apple.${p.replace(/\./g, "-")}.queue`,
    () => `sandbox profile applied — ${randInt(20, 300)} rules`,

    (p) => `APFS ${pick(APFS_OPS)} — "${pick(VOLUMES)}"`,
    () => `disk${randInt(0, 4)}s${randInt(1, 6)} online at /dev/disk${randInt(0, 4)}s${randInt(1, 6)}`,
    () => `volume "${pick(VOLUMES)}" mounted at /`,
    () => `container 0x${randHex(16)} — ${randInt(64, 4096)}GB capacity`,
    () => `fseventsd stream established for /private/var/folders`,
    () => `journal replay — ${randInt(0, 512)} transactions replayed`,
    () => `snapshot com.apple.os-snapshot-${randHex(16)} created`,

    () => `${pick(INTERFACES)}: ${pick(NETWORK_EVENTS)}`,
    () => `default route ${randIp()} via ${randIp()} on ${pick(INTERFACES)}`,
    () => `DNS server ${randIp()} added to resolver list`,
    () => `SSID association sequence initiated`,
    () => `WiFi channel ${randInt(1, 165)} width ${pick(["20MHz", "40MHz", "80MHz", "160MHz"])}`,
    () => `Bluetooth controller firmware ${randVersion()} loaded`,
    () => `NWPath satisfied — using ${pick(["Wi-Fi", "Ethernet", "Cellular"])}`,
    () => `interface ${pick(INTERFACES)} MTU ${randInt(576, 9000)}`,

    () => `${pick(SECURITY_EVENTS)}`,
    (p) => `SHA-256 digest verified for /System/Library/CoreServices/${p}`,
    () => `CSFlags 0x${randHex(6)} — hardened runtime`,
    () => `TCC access granted to ${MACOS_PROCESSES[randInt(0, MACOS_PROCESSES.length - 1)]} for AppleEvents`,
    () => `certificate "Apple Root CA" anchored`,
    () => `amfi_check_dylib_policy_self — allowed`,
    () => `SKEL audit token — euid 0, ruid 0, svuid 0`,

    () => `vm_allocate ${randInt(4, 512)}MB at 0x${randHex(12)}`,
    () => `mapped ${randInt(20, 800)} dylibs`,
    () => `jetsam limits — soft ${randInt(64, 512)}MB / hard ${randInt(512, 2048)}MB`,
    () => `memory pressure notification — level ${pick(["normal", "warning", "critical"])}`,

    () => `system sleep preventers — ${randInt(0, 5)} active`,
    () => `battery ${randInt(70, 100)}% — AC attached`,
    () => `SMC key PCPR = ${(Math.random() * 30).toFixed(2)} W`,
    () => `CPU die temperature ${randInt(38, 72)}.${randInt(0, 9)}°C`,

    () => `caught signal SIGSEGV at 0x${randHex(12)} — generating crash report`,
    () => `assertion failed: condition unreachable — aborting`,
    () => `watchdog timeout — process did not check in within ${randInt(10, 120)}s`,
    () => `low memory condition — releasing ${randInt(10, 300)}MB of cache`,

    () => `writing diagnostic data to /private/var/db/diagnostics`,
    () => `logd stream opened — streaming to unified log`,
    (p) => `analytics event queued — type com.apple.${p.split(".").pop() ?? p}.startup`,
    (p) => `oslog handle 0x${randHex(8)} — subsystem ${p}`,

    () => `configuration successfully applied`,
    () => `ready`,
    () => `startup complete in ${(Math.random() * 5000).toFixed(1)}ms`,
    () => `idle — waiting for next scheduled activation`,
    () => `registered with SystemConfiguration`,
];

function generateBootLogs(count: number): string[] {
    const logs: string[] = [];
    for (let i = 0; i < count; i++) {
        const ts = nextTimestamp();
        const process = MACOS_PROCESSES[randInt(0, MACOS_PROCESSES.length - 1)];
        const pid = randInt(1, 65535);
        const level = pickLogLevel();
        const message = pick(MESSAGE_GENERATORS)(process, pid) + pick(MESSAGE_GENERATORS)(process, pid) + pick(MESSAGE_GENERATORS)(process, pid) + pick(MESSAGE_GENERATORS)(process, pid);
        logs.push(`${ts} [${level}] ${process}[${pid}]: ${message}`);
    }
    return logs;
}

export const bootlog: string = [...generateBootLogs(2000), ...Array.from({length: 1000}, () => {
    return `Segmentation Fault (core dumped) at ${randHex(12)} ip ${randHex(12)} sp ${randHex(12)} error ${[4, 6, 7][Math.floor(Math.random() * 3)]} in libc.so`;
})].join("\n");